
env:
   global:
     - CONAN_REFERENCE: "ubitrack_tinyxml/2.5.3"
     - CONAN_USERNAME: "ubitrack"
     - CONAN_LOGIN_USERNAME: "ubitrack"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://conan.campar.in.tum.de/api/conan/conan-ubitrack"
     - CONAN_REMOTES: "https://conan.campar.in.tum.de/api/conan/conan-camposs"
     - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
